### ISSUE TITLE
Channels not working

### ISSUE THREAD

**Issue by Pinakin29** [botallen/repository.botallen#236]
Channels not working

**Comment by nsas02** [comment]
Yes, few channels are not playing

**Comment by Iamkillua** [comment]
Almost every channel is not working.

**Comment by tayde24** [comment]
Sony zee channels not working
Some free channels working

**Comment by nsas02** [comment]
> Sony zee channels not working Some free channels working

Only very few are working

**Comment by Prathamesh0070** [comment]
Not working

**Comment by Prathamesh0070** [comment]
https://user-images.githubusercontent.com/96067610/145839729-ac3f0cb8-23e3-4e8a-a310-d07eba1584f4.mp4

**Comment by iadisharma** [comment]
Channels of sony and zee are not working but Few other channels and all colors channels are working. please fix it

**Comment by iknothing** [comment]
yes same not working for me too

**Comment by rupmagic** [comment]
yes....nothing working for me

**Comment by iknothing** [comment]
mtv channels are working, but sony and zee are not

**Comment by babatunde6969** [comment]
None of the channels are working for me.

**Comment by ladlavj** [comment]
yes Sony channels are not streaming.. though thay streaming directly from jio app + wifi nw

**Comment by iMro0t** [comment]
this issue is fixed. update to version v2.2.2

**Comment by Asies23** [comment]
> this issue is fixed. update to version v2.2.2

Only 2.2.1 is available in repository

**Comment by iMro0t** [comment]
> > this issue is fixed. update to version v2.2.2
> 
> Only 2.2.1 is available in repository

Go to Addons and select Install from Repo then open the context menu of BotAllen Repo and click on "Check  for Update"

**Comment by Asies23** [comment]
> > > this issue is fixed. update to version v2.2.2
> > 
> > Only 2.2.1 is available in repository
> 
> Go to Addons and select Install from Repo then open the context menu of BotAllen Repo and click on "Check  for Update"

Thanks it's now working

**Comment by saumilwaghela** [comment]
@iMro0t issue still persist, reinstalled kodi 19.3, jio tv 2.2.2 from repo still

**Comment by MallikarjunKPatil** [comment]
> this issue is fixed. update to version v2.2.2

Thank you so much. Hats of to your work.

**Comment by MallikarjunKPatil** [comment]
> @iMro0t issue still persist, reinstalled kodi 19.3, jio tv 2.2.2 from repo still

Do clean install. I had done now. It's working for me. And while configuring the jiotv please use vpn. After installation is done you can turn off vpn.

**Comment by sampras55** [comment]
> 

It's showing update failed. Mine is still 2.2

**Comment by iknothing** [comment]
ok so guys here are the detailed steps i did to get it working.
step 1: clear data or remove old  jiotv addon from tv.
step 2: download and connect to vpn.
step 3:when connected follow procedure to reinstall jiotv and all of the setup and login,etc
step4:then go and turn off vpn.
step5:open kodi and play any thing, it should work.

**Comment by saumilwaghela** [comment]
@iknothing @iMro0t  reinstalled kodi 19.3, connected vpn  did all procedure, closed vpn it's not working sony Zee etc

**Comment by mhunny** [comment]
> ok so guys here are the detailed steps i did to get it working.
> step 1: clear data or remove old  jiotv addon from tv.
> step 2: download and connect to vpn.
> step 3:when connected follow procedure to reinstall jiotv and all of the setup and login,etc
> step4:then go and turn off vpn.
> step5:open kodi and play any thing, it should work.

Thanks that worked.
